### ISSUE TITLE
А edt умеет проверять обычные формы?

### ISSUE THREAD

**Issue by kuzyara** [Stepa86/edt-export#1]
Или как сделать чтобы не ругалось на общие модули обычных форм?
Как изменить режим на "Толстый клиент (обычное приложение)"?
![2019-06-05_16-38-42](https://user-images.githubusercontent.com/2604430/58946601-7943ef80-87b0-11e9-8827-8a2350bc2a72.png)

**Comment by Stepa86** [comment]
Обычные формы едт не загружает и не проверяет. На скриншоте ошибка в модуле объекта и видимо говорит о том, что в коде, который может быть серверным вызывается общий модуль РаботаСДиалогами, который серверным не является

**Comment by kuzyara** [comment]
Печалька.
